import type { Metadata } from "next";
import { montserrat400 } from "../fonts/montserrat";






export const metadata: Metadata = {
  title: "Codio | Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat400.className} min-h-screen overflow-hidden relative antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
